import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131313',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant': '#353534',
        primary: '#ffb4aa',
        'primary-container': '#ff5545',
        'on-primary': '#690003',
        'on-primary-container': '#5c0002',
        'primary-fixed': '#ffdad5',
        'primary-fixed-dim': '#ffb4aa',
        'on-primary-fixed': '#410001',
        'on-primary-fixed-variant': '#930005',
        'inverse-primary': '#c0000a',
        secondary: '#ffbc7c',
        'secondary-container': '#fe9400',
        'on-secondary': '#4b2800',
        'on-secondary-container': '#633700',
        'secondary-fixed': '#ffdcbf',
        'secondary-fixed-dim': '#ffb874',
        'on-secondary-fixed': '#2d1600',
        'on-secondary-fixed-variant': '#6a3b00',
        tertiary: '#e8b3ff',
        'tertiary-container': '#c567f4',
        'on-tertiary': '#510074',
        'on-tertiary-container': '#460066',
        'tertiary-fixed': '#f6d9ff',
        'tertiary-fixed-dim': '#e8b3ff',
        'on-tertiary-fixed': '#310048',
        'on-tertiary-fixed-variant': '#7201a2',
        error: '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'on-background': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e7bdb7',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#ad8883',
        'outline-variant': '#5d3f3b',
        'surface-tint': '#ffb4aa',
        success: '#4ade80',
      },
      fontFamily: {
        headline: ['"Space Grotesk"', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        hard: '4px 4px 0px #000000',
        'hard-sm': '2px 2px 0px #000000',
      },
    },
  },
  plugins: [],
} satisfies Config
